### ISSUE TITLE
Create a parser for the new markdown format for mentorship data

### ISSUE THREAD

**Issue by KDwevedi** [Code4GovTech/server#16]
### Description
Mentorship program data will be collected weekly through pull requests to the new [c4gt milestones website](https://github.com/Code4GovTech/c4gt-milestones).

### Tasks
- [ ] Create a parser to go through the markdown and categorise data
- [ ] Create a scraper tool to scrape relevant links as they are mentioned in the markdown
- [ ] Finalize tables in the database to store this data

### References
- [The reference markdown](https://github.com/Code4GovTech/c4gt-milestones/blob/main/docs/2023/Yaus/Frontend%20And%20Deep%20Linking/updates/2023-07-07.md)
- [Mistune Markdown Parser](https://pypi.org/project/mistune/)
